from django.urls import path
from .import views
urlpatterns =[
    # 首页
    path('index', views.index),
    # 登录
    path('login', views.login),
    # 退出登录
    path('log_out', views.log_out),
    # 注册
    path('regist', views.regist),
    # 系统的登录日志
    path('login_log', views.login_log),
    # 用户管理
    path('user_info', views.user_info),
    # 删除用户
    path('user_delete/<str:username>/<str:password>', views.user_delete),
    # 修改用户
    path('user_alter/<str:username>/<str:password>', views.user_alter),
    # 创建信息 guest_profile_edit
    path('guest_profile_edit', views.guest_profile_edit),
    # 完善信息 guest_profile_edit_upload
    path('guest_profile_edit_upload', views.guest_profile_edit_upload),
    # 首页
    path('guest_index', views.guest_index),
    # 信息展示
    path('guest_profile_display', views.guest_profile_display),
    # 测试页面
    path('test', views.test),
    # 邮件发送
    path('email_editor', views.email_editor),
    # 邮件删除
    path('email_manage/<int:id>', views.email_manage),
    # 邮件展示
    path('email_presentation', views.email_presentation),
    # 邮件单条展示email_single_presentation
    path('email_single_presentation', views.email_single_presentation),
    # 找回密码
    path('reset_password', views.reset_password),
    # 修改密码
    path('change_password/<int:user_id>', views.change_password),
    # 类别管理
    path('manage_categories', views.manage_categories),
    path('delete_category/<int:category_id>', views.delete_category),
    # 用户上传二手商品
    path('upload_item', views.upload_item),
    path('item_list', views.item_list),
    # 管理员管理商品的妆态
    path('admin_review', views.admin_review),
    # 删除所有的商品
    path('delete_second_items_all', views.delete_second_items_all),
    # 展示代售商品
    path('available_items', views.available_items),
    # 待发货
    path('filtered_items', views.filtered_items),
    # 我的订单
    path('buyer_view', views.buyer_view),
    # 删除商品
    path('delete_item', views.delete_item),
    # 展示商品详情
    path('item_detail/<int:item_id>', views.item_detail),
    # 我要收藏
    path('add_to_favorites', views.add_to_favorites),
    # 我要收藏
    path('my_favorites', views.my_favorites),
    # 我的浏览
    path('browsing_history', views.browsing_history),
    # 我的推荐
    path('recommend_items_collaborative_filtering', views.recommend_items_collaborative_filtering),
    # 游客浏览
    path('visitor_index', views.visitor_index),
    # 用户的购物车
    path('my_cart', views.my_cart),
    path('remove_from_cart/<int:item_id>', views.remove_from_cart),
    path('checkout_item/<int:item_id>', views.checkout_item),
    # 我赚到的钱
    path('earned_money_view', views.earned_money_view),
    path('delete_user/<int:user_id>', views.delete_user),
    path('user_list', views.user_list),
    path('edit_user/<int:user_id>', views.edit_user),
    ]
